;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "github-repo-config-skill")
(def path ".")
(def version "0.1.2")
(def tag "0.1.2")
(def generated-at "2020-05-27T23:21:30Z")
