;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "github-repo-config-skill")
(def path ".")
(def version "0.1.4")
(def tag "0.1.4")
(def generated-at "2020-05-28T00:03:37Z")
